# Generated by Django 4.1 on 2022-08-21 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField()),
                ('operatorcode', models.IntegerField()),
                ('tag', models.CharField(max_length=10)),
                ('utc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('message', models.TextField()),
                ('operatorcode', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=10)),
                ('endtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendtime', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notification_service.client')),
                ('mailings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notification_service.mailing')),
            ],
        ),
    ]
