# Generated by Django 4.0.7 on 2022-08-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operatorcode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='sendtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
